server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: mybookstore-api
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_NAME:mybookstore}
    username: ${USER_NAME:root}
    password: ${PASSWORD:damian}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate